//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoClienteWS.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://cocacola.com/")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private System.Nullable<int> PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cocacola.com/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://cocacola.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.com/HelloWorld", ReplyAction="*")]
        ProyectoClienteWS.ServiceReference1.HelloWorldResponse HelloWorld(ProyectoClienteWS.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoClienteWS.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ProyectoClienteWS.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name listarResult from namespace http://cocacola.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.com/listar", ReplyAction="*")]
        ProyectoClienteWS.ServiceReference1.listarResponse listar(ProyectoClienteWS.ServiceReference1.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.com/listar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoClienteWS.ServiceReference1.listarResponse> listarAsync(ProyectoClienteWS.ServiceReference1.listarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://cocacola.com/", Order=0)]
        public ProyectoClienteWS.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProyectoClienteWS.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://cocacola.com/", Order=0)]
        public ProyectoClienteWS.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProyectoClienteWS.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listar", Namespace="http://cocacola.com/", Order=0)]
        public ProyectoClienteWS.ServiceReference1.listarRequestBody Body;
        
        public listarRequest() {
        }
        
        public listarRequest(ProyectoClienteWS.ServiceReference1.listarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarRequestBody {
        
        public listarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarResponse", Namespace="http://cocacola.com/", Order=0)]
        public ProyectoClienteWS.ServiceReference1.listarResponseBody Body;
        
        public listarResponse() {
        }
        
        public listarResponse(ProyectoClienteWS.ServiceReference1.listarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.com/")]
    public partial class listarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoClienteWS.ServiceReference1.Productos[] listarResult;
        
        public listarResponseBody() {
        }
        
        public listarResponseBody(ProyectoClienteWS.ServiceReference1.Productos[] listarResult) {
            this.listarResult = listarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ProyectoClienteWS.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ProyectoClienteWS.ServiceReference1.WebService1Soap>, ProyectoClienteWS.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoClienteWS.ServiceReference1.HelloWorldResponse ProyectoClienteWS.ServiceReference1.WebService1Soap.HelloWorld(ProyectoClienteWS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ProyectoClienteWS.ServiceReference1.HelloWorldRequest inValue = new ProyectoClienteWS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProyectoClienteWS.ServiceReference1.HelloWorldRequestBody();
            ProyectoClienteWS.ServiceReference1.HelloWorldResponse retVal = ((ProyectoClienteWS.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoClienteWS.ServiceReference1.HelloWorldResponse> ProyectoClienteWS.ServiceReference1.WebService1Soap.HelloWorldAsync(ProyectoClienteWS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoClienteWS.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ProyectoClienteWS.ServiceReference1.HelloWorldRequest inValue = new ProyectoClienteWS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProyectoClienteWS.ServiceReference1.HelloWorldRequestBody();
            return ((ProyectoClienteWS.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoClienteWS.ServiceReference1.listarResponse ProyectoClienteWS.ServiceReference1.WebService1Soap.listar(ProyectoClienteWS.ServiceReference1.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public ProyectoClienteWS.ServiceReference1.Productos[] listar() {
            ProyectoClienteWS.ServiceReference1.listarRequest inValue = new ProyectoClienteWS.ServiceReference1.listarRequest();
            inValue.Body = new ProyectoClienteWS.ServiceReference1.listarRequestBody();
            ProyectoClienteWS.ServiceReference1.listarResponse retVal = ((ProyectoClienteWS.ServiceReference1.WebService1Soap)(this)).listar(inValue);
            return retVal.Body.listarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoClienteWS.ServiceReference1.listarResponse> ProyectoClienteWS.ServiceReference1.WebService1Soap.listarAsync(ProyectoClienteWS.ServiceReference1.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoClienteWS.ServiceReference1.listarResponse> listarAsync() {
            ProyectoClienteWS.ServiceReference1.listarRequest inValue = new ProyectoClienteWS.ServiceReference1.listarRequest();
            inValue.Body = new ProyectoClienteWS.ServiceReference1.listarRequestBody();
            return ((ProyectoClienteWS.ServiceReference1.WebService1Soap)(this)).listarAsync(inValue);
        }
    }
}
